### ISSUE TITLE
The windows name needs consistency.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#10]
The windows name has the _python3_ placeholder or _Mi aplicación_ in some cases. it will be good determine a name for the window that is consistent across the entire application.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/0898be12-4c27-42eb-9ccd-23772eb5df9f)

**Comment by Elmerluis0129** [comment]
Listo, ya arreglé esto. 

Poniendo al menú:

Menú - Módulo (Número del módulo correspondiente)

Y a las ventanas de las lecciones:

Aprendiendo Python - Lección (Número de la lección correspondiente)
