### ISSUE TITLE
Correción de Pantalla inicial

### ISSUE THREAD

**Issue by inghsantillan** [lopezbec/AI_Gamification_Python#103]
![001 pantalla inicial](https://github.com/user-attachments/assets/947b510e-9832-49eb-84de-557fc7cacd1e)

En la barra superior, dice "Bienvenidos" 

Debe de aparacer el nombre de la pagina en la cual esta, tales como:

Cuestionario Hexad-12
Menu principal
Module 1 leccion 1, ......

**Comment by DLeonProyects** [comment]
Voy a trabajar en ello.
