### ISSUE TITLE
Inicio del cuestionario

### ISSUE THREAD

**Issue by inghsantillan** [lopezbec/AI_Gamification_Python#104]
Cuestionario previo al juego.
Feedback: Podría mostrarse el nombre del juego en la parte superior de la ventana, en lugar de decir “python”.

![001 pantalla cuestionario](https://github.com/user-attachments/assets/b4310c01-520f-4076-895b-61270c1b6998)

**Comment by DLeonProyects** [comment]
Voy a trabajar en ello.

**Comment by lopezbec** [comment]
Closing since it is the same as issue #103
