### ISSUE TITLE
Diseño de pantalla de módulos

### ISSUE THREAD

**Issue by inghsantillan** [lopezbec/AI_Gamification_Python#107]
Modulos para juego
![005 modulos](https://github.com/user-attachments/assets/99baa84e-2683-4c00-a5bc-4fc05bc18092)

Feedback: se observan los botones muy separados y podrían tener formas más dinámicas que motiven a hacer click.
(moved this 2nd part to another issue)

**Comment by DLeonProyects** [comment]
Trabajare en ello.

**Comment by DanielDD-UNPHU** [comment]
Que tal este nuevo diseno de botones?


![image](https://github.com/user-attachments/assets/a49195f0-78ca-44ba-95dc-cc6ac90c6a11)

**Comment by lopezbec** [comment]
Look ok to me (even though I am not the best to ask :P)  you can make it a bit larger, to reduce the space in between and add the "accent" to the word "modulo"

**Comment by DLeonProyects** [comment]
Thank you for your feedback! I will make the suggested adjustments to increase the size, reduce the spacing, and add the accent to the word "módulo."

**Comment by DanielDD-UNPHU** [comment]
Le he agregado un ancho mayor y mas altura a los botones de Modulo, que tal se ven ahora?.


![image](https://github.com/user-attachments/assets/f1fe0d0b-fa34-4d8e-b14c-b3247bff414c)

**Comment by DanielDD-UNPHU** [comment]
He realizado los ajustes correspondientes a las dimensiones de los botones en el módulo. Para facilitar futuros cambios, he añadido un comentario en el código que indica claramente la sección relevante. Cualquier modificación posterior de las dimensiones puede hacerse directamente en esta sección:


```
# Para cambiar las dimensiones de los botones Modulo.
modulos_btn.setFixedSize(171, 80)  # Ajusta el tamaño (ancho, alto) // Botones Modulo 1, Modulo 2, etc.
```


![image](https://github.com/user-attachments/assets/9514e6e7-d6e7-4530-9dba-c05f6bfce69f)

Demostracion:

![image](https://github.com/user-attachments/assets/8e6b092a-e05f-41e8-8c17-6bffcf3d0850)
