### ISSUE TITLE
Mensaje al tratar de acceder module avanzado

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#109]
Modulos para juego
![005 modulos](https://github.com/user-attachments/assets/99baa84e-2683-4c00-a5bc-4fc05bc18092)

Al hacer click en un módulo muy avanzado, debe generar un error/mensage que indique:   "Aún debes de completar el módulo anterior"

**Comment by PriBaez** [comment]
@lopezbec with the last email about this issue, Im gonna unassigned me cause is a low prioritie.

![image](https://github.com/user-attachments/assets/4bcdb18b-9bdc-4419-964e-915eb6bed95f)

**Comment by Elmerluis0129** [comment]
Later will be tackling this issue if needed.
