### ISSUE TITLE
Fix spacing and word wrap in the app.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#11]
The content has a wide spacing and the words overflow through the window, making impossible to see part of the content.
There are properties in PyQt for adjust this.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/07119f18-26e2-4d3a-aa59-d8f5415d695a)

**Comment by Elmerluis0129** [comment]
I've been trying to eradicate that wide spacing, but I couldn´t. Don't know why, every single methodology, or properties it didn't work at all.  I'll try this later. Since it's not critical.

**Comment by PriBaez** [comment]
@Elmerluis0129 use ChatGPT for that or do some research.

**Comment by Elmerluis0129** [comment]
This one has been fixed already. @josealfredomatias493 did it.
