### ISSUE TITLE
Show Point in main menu

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#115]
I don't recall if we already had it like this or if something got changed along the way.  But the current Points of the users should also be shown in the main menu when the "point" feature is enabled. 

If the point feature is disabled it should not be shown in the main menu or the pages of the lesson. For now it is ok to show in the leaderboard when the leaderboard  feature is enable

![image](https://github.com/user-attachments/assets/b8346805-f41c-4a66-b1b8-06d820676c59)

![image](https://github.com/user-attachments/assets/9275e634-648e-4b99-a7dc-5115346fcff5)

**Comment by PriBaez** [comment]
@lopezbec the point feature always been in the lesson but not in the menu.

**Comment by lopezbec** [comment]
ok, thanks.

In that case, ensure the current points show up in the modules since it looks like it goes back to 0 or show the points gained on that specific module.

Also, it would be good to have a points feature in the main menu too
