### ISSUE TITLE
App closes when moving forward after entering name instead of opening survey

### ISSUE THREAD

**Issue by DanielDD-UNPHU** [lopezbec/AI_Gamification_Python#127]
Cuando un nuevo usuario ingresa a la aplicación y escribe su nombre en el campo correspondiente, al presionar el botón "Siguiente", la aplicación se cierra inesperadamente. El comportamiento esperado es que, después de presionar "Siguiente", se abra la encuesta para que el usuario pueda continuar con el flujo de la aplicación.

**Pasos para reproducir:**

1. Abrir la aplicación.
2. Ingresar un nombre en el campo correspondiente.
3. Presionar el botón "Siguiente".
4. Observar que la aplicación se cierra en lugar de abrir la encuesta.

**Comment by PriBaez** [comment]
This issue is already solved with the last merge of @Elmerluis0129
