### ISSUE TITLE
Complete page_order.json structure

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#129]
The file is incomplete, it only goes up to module 2. It is necessary to complete it and check that the keys have the correct values, here a quick explanation:

- "quiz_number": the number of the quiz (usually 1 or 2, you can check it in the suffix Q1, Q2...)
- "sections": these are the sections or parts of a quiz, to know how many there are and what type, check the file referring to that quiz (for example for the first quiz of the first module, the M1_Q1_Main.json would be checked) and how many page_type keys it has.

**Comment by josealfredomatias493** [comment]
@PriBaez  This issue is completed. I'll just wait for @lopezbec to confirm, for me to merge with main.

**Comment by lopezbec** [comment]
@PriBaez  pls take a look and confirm it it can be merge

**Comment by PriBaez** [comment]
@lopezbec, I'll check it out in the afternoon
