### ISSUE TITLE
Keep the consistency in the space for complete de blank spaces.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#13]
Sometimes a single underscore can be confused with a minus in a quick lecture of the sentences, keep in mind to use two underscores or four underscores for larger responses.

![image (2)](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/c4fc2ce5-50cb-4817-8b93-c2f0672a2044)

**Comment by Elmerluis0129** [comment]
Ok, this one I would do it later. Since this one is not a critical one.
