### ISSUE TITLE
The window extends to the right when you click to verify the response.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#14]
The page extends to the right when the veracity of the answer is verified. This is an improvement point to be tackled in terms of UX/UI consistency.
_Before to verify response_
![image (1)](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/2eef96bc-7a86-4b48-b758-68911f358aac)

_After to verify response_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/77696988-20e2-4265-a175-de74134538fe)

**Comment by Elmerluis0129** [comment]
This one I haven't noticed before, It might be just in your device. Anyways give me the module, in order to get there and check it out. To see if I can fix it.

**Comment by PriBaez** [comment]
@Elmerluis0129 here, Module 1, lesson 5, page 11.
Ask for help to check if it is something on your laptop or if it is a failure that is only replicated in mine.

**Comment by PriBaez** [comment]
@Elmerluis0129 my bad. 
Module 1, lesson 2, page 3.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/97679faa-144c-4d30-bcd9-f0f820d44089)

**Comment by Elmerluis0129** [comment]
Issue cerrado, Revisé y no encontré el error. Nunca se me desplazó o algo al verificar. Abrir de nuevo si es necesario.
