### ISSUE TITLE
Progress Bar in lessons reset to 0%

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#140]
After completing the lessons and quizzes from certain module the progress bar percent is set to 0%. 
![image](https://github.com/user-attachments/assets/4eabf613-2e28-4bdf-8147-8c41492f3dd2)

**Comment by Elmerluis0129** [comment]
Fixed !

**Comment by Elmerluis0129** [comment]
@PriBaez @lopezbec
