### ISSUE TITLE
Writing/Syntax errors in pedagogicals sections

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#15]
There are codes of examples in the pedagogical sections that have errors. Causing syntax errors in the code

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/32c48d1f-e807-4613-ba6a-5203f51677f8)
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/e850dcb2-cf11-42b0-b293-c9c6e9de385f)

**Comment by Elmerluis0129** [comment]
I´ll check it out. 

Two things:

Give me the path wherever you noticed the errors. Ex: Module 3, Lesson 2, Json part 1
If you can specify the error would be helpful

**Comment by PriBaez** [comment]
Estos los estaba trabajando yo @Elmerluis0129. Al final asi es como debe de ir.
