### ISSUE TITLE
Refine lesson unlock logic

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#16]
Currently, there are two situations identified where the lock/unlock logic breaks:

- Redoing a lesson removes the completion check and shows, once again, the open padlock
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/a5121b02-c9ba-4138-9211-9267580b0adb)

- If you open a lesson, which you must complete to continue, and close it at any time before completing it, this unlocks the next one without needing to continue or complete with the first one.
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/3a0a81d3-26fd-40c5-9fc3-5722f3a62fee)

**Comment by Elmerluis0129** [comment]
Here the first one has been fixed already. Since not matter how many times you redo a lesson, Once is completed it doesn't show the open padlock anymore.

The second one I've been trying to fix it. Once done. I will close this issue.

**Comment by Elmerluis0129** [comment]
Issue Finished already! Just missing to put the icon but that could be another issue talking about it. @PriBaez @lopezbec
