### ISSUE TITLE
Deformation when resetting responses in drag and drop

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#17]
In some drag and drop, selecting the wrong answer and clicking restart deforms the content very unusually, making it uncomfortable to solve the problem.

- _Example 1_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/244dc68e-0058-4efd-a79a-10eaef059b66)

- _Example 2_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/172cae7e-b7f2-4c30-b787-35f72f33b758)

**Comment by Elmerluis0129** [comment]
Got it. I'll work on it later.

**Comment by Elmerluis0129** [comment]
Ready, Daniel was trying to fix it by coding, he found a way to fix this, so I took that code, I integrated with the main code, and it did work. So it's already fixed. @DanielDD-UNPHU @lopezbec @PriBaez
