### ISSUE TITLE
Create a difference between executable code and questions example.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#18]
Create a different color scheme or use a different font between the executable console code and the examples of the questions to be answered.

_Executable code_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/b76ab108-87ec-45fe-a74e-bb947d97d58b)

_Not executable code_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/bb9e10f5-ad26-4388-9032-8eb72bf3f72d)

_Not executable code_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/a59eb125-b3e4-47ca-a376-f15d2920e3fb)

_Not executable code_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/38f18c39-65d6-45ca-98eb-eb6703fcea40)

**Comment by Elmerluis0129** [comment]
Since this one is not critical. I will work on it once i finished every single critical ones.
