### ISSUE TITLE
Bug: Selecting the correct answer is not allowed.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#19]
In module 4, lesson 2 page 2 has a bug type that does not allow the correct answer to be selected as valid (I found that none of the three options is marked as good).

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/8ee038af-5528-40ad-b12e-5cb0294c73ec)

**Comment by Elmerluis0129** [comment]
This one has been fixed already. Thanks
