### ISSUE TITLE
Bug: Continuing to fill the blanks spaces is not allowed.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#20]
In module 4, lesson 3, page 2 it has a defect that does not allow to continue filling in the blanks spaces.

_Before you complete_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/59a83f27-e0d6-496e-9cee-b684e3db20fb)

_After you complete_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/5f67ef43-ccbc-4424-a298-3fdd585c632e)

**Comment by Elmerluis0129** [comment]
Thanks. This one has been fixed.
