### ISSUE TITLE
Sample executable code should show an output.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#21]
Example codes (pedagogical) should be able to show their results, there are some that do not have as this case in module 4, lesson 4, page 7.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/fa1429e9-529f-4588-bb9c-7f8e1b3741a8)

**Comment by Elmerluis0129** [comment]
Ok, When I was implementing that I tried to do it in every single one. It looks like some of them I forgot. So, Specify the path where you identified those ones. 

Module 4, lesson 4, page 7 is fixed already. I will close this issue if you can't identify any other..

**Comment by PriBaez** [comment]
@Elmerluis0129 close the issue then, it can be recreated in the case of missing examples.
