### ISSUE TITLE
DASHBOARD - Fix Early Access to Later Lessons

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#22]
**English:** In the Lessons field, you should not allow the user to access other lessons if the current lesson is not yet completed.
Currently there is a code to control that, but it is poorly structured, since just by pressing lesson 1, the user can access lesson 2 without having to finish lesson 1, and even by just pressing lesson 1, you can enter to the other lessons.

![Imagen1](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/4bd25f1f-cd19-4695-a18c-159edcdd9bda)

Test: Unlock all lessons.

![Imagen2](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/723b00f2-17ec-4454-820a-30be72608909)

In this image you can see how the program detects that lesson 3 is completed, without yet finishing lesson 2. On the other hand, it detects that I have already completed lesson 1 and 3, without being completed.

![Imagen3](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/ed9840e9-87fb-46cc-9333-11057b55b46f)

**Comment by PriBaez** [comment]
@DLeonProyects that issue is already in the board. See #16

**Comment by lopezbec** [comment]
Closing since it is already in the board. See https://github.com/lopezbec/AI_Gamification_Python/issues/16
