### ISSUE TITLE
Inconsistency in the Display of "Winning XP" and "Leaderboard" after Restarting Exercise

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#26]
When you are in an exercise and press the "Reset" button, the sections showing "Winning XP" and "Leaderboard" are immediately hidden. However, when you advance to the next screen, these sections reappear.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/390088c2-2aad-4a77-9ca8-4f0b83ab1447)

You can see how after respawning the XP has been erased and starts from 0.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/393d0213-cc0b-431d-a850-ef169bf7226d)

By answering correctly and advancing to the next slide, the XP Earned is reset to 0.

Demonstration:

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/19fd0ab3-a7b8-48a9-aad1-e8ecc2a01589)

EARNING XP:

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/45bd44ce-fa58-4fe8-ab72-65e531b4fc38)

NEXT SLIDE:

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/b0d0287a-e596-459e-a309-47212dab586a)

**Comment by Elmerluis0129** [comment]
The 2nd part about the restarting of the points once you move on it's already fixed! Imma close this issue once I finish the first part about the reset button.

**Comment by Elmerluis0129** [comment]
Sorry. Imma close this issue. Since the first concerned about the reset button was mentioned in another issue already. It has its own issue section. Since that. This issue it's been fixed already talking about the restarting the points once you moved on.
