### ISSUE TITLE
Unexpected Window on Pressing 'Restart' in Lesson 3, Page 5

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#30]
When you press the restart button, a window is added below that does not appear when you enter the slide, it only appears when you press restart.

When we enter the slide it looks like this:
<img width="1339" alt="image" src="https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/4004f55f-a1cb-4060-8a0b-1101ebb2a111">

AFTER PRESSING THE RESET BUTTON:

<img width="1345" alt="image" src="https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/4e622372-2fda-46eb-a484-d633c7878dd2">

IN LESSON 3 PAGE 8 OF 11, THE SAME THING HAPPENS AS IN LESSON 3 PAGE 5 OF 11 WHEN YOU PRESS RESET, THESE NEW FIELDS APPEAR:

Before:
<img width="1361" alt="image" src="https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/5b81ef96-802a-43eb-ba00-ae050ee0c902">

After:

<img width="1349" alt="image" src="https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/7084f334-afc1-47bd-a0d3-582f8cf6b9c9">

**Comment by Elmerluis0129** [comment]
Imma close this issue. Since it was already detected, and an issue section was already opened with this issue. Called: Deformation when resetting responses in drag and drop #17.
