### ISSUE TITLE
Repetitive Placement of Correct Answers in Lesson 5, Except on Page 15 of 18

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#31]
Page 8/18:

<img width="1356" alt="image" src="https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/bced04a7-c1f8-426f-bddf-9724017c88bf">

Page 10/18
<img width="1388" alt="image" src="https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/33678367-898d-48f1-a0e6-6ff4e866f613">

Page 11/18:

<img width="1377" alt="image" src="https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/9ffb1260-8c3d-4914-86e1-993567977fc3">

**Comment by Elmerluis0129** [comment]
I already fixed this one. Imma close it. Thanks!
