### ISSUE TITLE
Missing Transition to Practice Section in Lessons

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#32]
When we finish a lesson there is still no code to control the practices of the lessons

<img width="1377" alt="image" src="https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/08ec922b-3a71-48c1-8d82-baceceec95b9">

**Comment by Elmerluis0129** [comment]
This one would be in a few months. Since we are not working with the practice lesson yet. Meanwhile this issue will be open.

**Comment by lopezbec** [comment]
Added a code in the main directory ("[command_line_UI.py](https://github.com/lopezbec/AI_Gamification_Python/blob/main/command_line_UI.py)") to be use as foundation to complete this issue

**Comment by Elmerluis0129** [comment]
@lopezbec  I already integrated the CMD so it's just missing the answer to all the practices sections in every single lesson of every single module. So, I'm going to close this issue please re open it once the answers are gathered already.
