### ISSUE TITLE
The statement doesn't match with the code

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#33]
The statement asks to the player to add 55 and 7 but in the code is adding 2 and 4. This error is on module 2, lesson 2, page3.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/edb9d6aa-0610-4c38-9e71-579eb2ae89a7)

**Comment by Elmerluis0129** [comment]
If you add an issue like this, You MUST specify where it is. Example. Module x, Lesson x, Part x. Otherwise it would take too much to the person working with this in order to identify where it is.
