### ISSUE TITLE
Link the "user name" input page with the Leaderboard

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#35]
From the "intro pages" @PriBaez  created, the name users input on it needs to be linked with the Leaderboard of the application. At the beginning of the application the "new user" should be in the last place, as they go and complete the app, the Leaderboard should rank users based on "their points" (that is, based on the new user/real user score, and all the "fake users points). The fake user points might need to be updated to reflect the maximum score a user can get in the app.

Here is the "user name" input page 

![usename_input](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/6aca2604-e7f0-451f-9df7-f3856e3e2247)

**Comment by PriBaez** [comment]
The name of the current users is now implemented in the leaderboard successfully. For reference the next image the current player is Lucas with a score equals to Zero. 

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/9ea3a6d7-07d6-44ec-a2b7-3d818801501c)
