### ISSUE TITLE
Reduce Fake users in leaderboard to 4-5

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#37]
It is necessary to reduce the number of "fake users" to 4 or 5 consistently in all implementations of the Leaderboard and make these users as real as possible (instead of user 1, a name like Henry Ford should be placed)

**Comment by lopezbec** [comment]
Since this would be for Spanish-speaking users, the names should be Spanish ones, you could use your name if you wanted but not English names

**Comment by DLeonProyects** [comment]
solved

**Comment by lopezbec** [comment]
In the leaderboard of the "menu" page there still 18 usres

**Comment by Elmerluis0129** [comment]
Fixed!

**Comment by PriBaez** [comment]
The fake users in leaderboard were increase testing the new features.

**Comment by Elmerluis0129** [comment]
Im working on this, I already reduced the users Ill be pushing it for tomorrow ! @lopezbec @PriBaez

**Comment by lopezbec** [comment]
@Elmerluis0129 make sure to test it so it does not have to be re-open again

**Comment by Elmerluis0129** [comment]
Fixed ! @lopezbec @PriBaez
