### ISSUE TITLE
Need to recognized new VS old users

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#40]
The app should be able to identify new users from old users (that is users that have already played).  This should be achieved by using their user name.

If a new user is playing the game they should see the "normal" sequence of pages. That is, after they type their user name, they should see the hexad questionnaire, the ready-to-learn page, and the main menu page (see image below).

If an old user enters again ( that is the same user name is entered /a repeated user name) they should be taken directly to the main menu page, skipping the hexad questionnaire. The main menu page should reflect their progress in all the appropriate places (like leaderboard, point, modules unlocked, etc).  

This is what I am calling the main menu page

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/352cdeea-f759-461b-9259-f138e1238877)

**Comment by Elmerluis0129** [comment]
I did it already, I'm going to close this issue feel free to re-open if necessary.
