### ISSUE TITLE
Leaderboard users need to be sorted

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#41]
You need to sort the leaderboard users by score so that the lowest score (normally a new user which score is 0) is at the bottom.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/5e3735ed-1d6c-4ea3-882a-22a37e5a56f9)

**Comment by lopezbec** [comment]
This has to happen automatically. That is, every time the users open the Leaderboard, they should see a sorted board without the need to specify by which columns it needs to be sorted (as the old implementation that tried to fix this).

The user can only impact/affect the leaderboard indirectly, by typing their name and getting more scores.
