### ISSUE TITLE
Leaderboard score of "user" not updating

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#42]
The score of the user on the leaderboard is not been updated. After completing module 1, lesson 1, the score on the leaderboard is still 0.

**Comment by PriBaez** [comment]
@lopezbec  with the solution for the issue #40 a new bug appeared in the leaderboard for the old users. The current user's name is not displayed. 
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/9f3b3c98-da0a-4348-8f41-5261edb07cfa)

**Comment by Elmerluis0129** [comment]
Already finished! @lopezbec @PriBaez
