### ISSUE TITLE
Removal of the "Presionar al completar lección" button

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#45]
This button was created as a workaround but the correct thing is that the lessons are unlocked automatically when fully completed without the user having to do anything additional.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/60c5d611-3a53-40b1-ae33-e6450456d2ea)

**Comment by Elmerluis0129** [comment]
@josealfredomatias493 Esto no es tan facil como ir al codigo y quitar el boton (YA que el boton tiene una funcion unica) Hasta que no se logre esa funcion sin el boton, no se puede eliminar, que es el mismo problema que venimos enfrentando desde el inicio de las logicas de candados. si logras hacerlo mandamelo primero porque esta alternativa es la que mas se acerca a tener arreglado toda la logica de bloqueo.

**Comment by josealfredomatias493** [comment]
Buen día @Elmer Luis Saint-Hilare Rojo ***@***.***>,

Estaba probando pero no ví muchos cambios sin el botón. Voy a probar esta
semana y veré como puedo lograr la lógica de candado. Cualquier cosa te
aviso.

Saludos,
JM
