### ISSUE TITLE
Color change for selected row in leaderboard

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#46]
When a row is selected, the text color has little contrast with the background. This makes it impossible to see the text in those cases. It is required to change the color of the underlined text to another that achieves the desired contrast for improved visibility.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/c59a57a1-ab74-4732-a9b9-783ccf291a02)

**Comment by lopezbec** [comment]
The leaderboard should not be interactive per se. This means that the user should not be able to modify anything directly. The Leaderboard should only be updated by the app based on the user score.  

The only thing we could add to the leaderboard would be to highlight the user's name itself. It can be done by making the user's name Bold or having the row with the user info in a different color.

**Comment by PriBaez** [comment]
@lopezbec That's what I mean. When you select or position the cursor over an X cell, the letters turn white as shown in the image, making it difficult to read in that case.
