### ISSUE TITLE
Creating a Persistent Tracking Code for Completed Lessons

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#47]
Develop code that, after a user completes a lesson, retains the information that the user completed said lesson even after closing and reopening the program. Upon confirming the completion of the lesson, when opening the lesson again the program should display a "Lesson Completed" message and offer two options via buttons: "Repeat lesson" or "Exit lesson".

**Comment by DLeonProyects** [comment]
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/623d41d2-3c80-48b1-b389-7af48b1f32c2)

**Comment by DLeonProyects** [comment]
Importante: Se deberia agregar una estructura que muestre con color claro o con un candado las lecciones que ya estan completadas.

**Comment by lopezbec** [comment]
Most of this is already implemented, the only thing that can be added is to change the color of the "module" on the drop menu to clearly show which ones are pending, completed, or not started yet (see image below)


![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/a291e04c-3e24-4f72-90cb-c721a8cbcc8f)

**Comment by Elmerluis0129** [comment]
Issue completed already.
