### ISSUE TITLE
Error with Module 1 Lesson 2

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#50]
There is a bug in the code that is closing the window in Module 1, Lesson 2, page1 (see below)

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/8dc362a8-5c1a-48c1-b7b6-7152a37482b8)

**Comment by lopezbec** [comment]
If this is a library version control issue with need to add a script that install/check all necessary libraries version before opening the app

**Comment by PriBaez** [comment]
@lopezbec the problem is not about version control (although having a script that installs all the necessary dependencies would be a plus). The error seen in the console is about the btn_open_console attribute that does not exist in that class. I'll be checking that out in a moment.
