### ISSUE TITLE
Navigation Flow Correction: Direct Access to the Dashboard After Sending Correct Answer in Decision Making

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#52]
In the decision-making section of our app, there is currently an issue with navigation and UI fluidity. Upon completing the decision-making process, the user selects a response and proceeds to submit it. It would be expected that after submitting the correct response, the application would automatically redirect the user to the Dashboard to view the next step. However, this flow does not occur as expected.

Instead of a direct transition to the Dashboard, the user is faced with the need to perform an additional action: he must manually close the decision-making window. Only after performing this action, the application proceeds to open the Dashboard. This behavior adds unnecessary steps and affects the user experience, breaking the fluidity and intuitiveness of the process.

Error page:

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/1f63677f-5371-4d07-ba89-83c0d184b297)

After closing decision making manually, open the Dashboard:

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/35702efc-59af-4ae8-adc9-158afebc6bfd)

**Comment by Elmerluis0129** [comment]
Let me see if i got what is asked. Basically, once the user sends the last answer it should automatically close the current window which is expected to be the question one and then automatically proceed opening the Menu? @lopezbec @DLeonProyects

**Comment by Elmerluis0129** [comment]
Fixed already!
