### ISSUE TITLE
Implement Form Validation: Restrict Progress with Empty Name Field or Invalid Texts

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#53]
Currently, in our application, we have detected a limitation in the validation process of the form where the User Name is entered. In its current state, the form allows users to proceed to the next step even if the Name field is empty or contains invalid text, such as symbols or illegal characters. This lack of validation could lead to data problems and affect the quality of the information collected.

The absence of adequate validation in this essential field can lead to the accumulation of incorrect or incomplete data in our database, which could negatively affect data analysis and decision making based on this information.

It is proposed to implement a validation mechanism for the Name field in the form. This mechanism must:

**1. Prevent the user from proceeding to the next step if the field is empty.**
**2. Validate that the entered text is appropriate, restricting the use of symbols and characters that are not permitted.**
**3. Provide immediate visual feedback to the user if an invalid entry or empty field is detected, possibly through an error message or highlighting of the field in question.**

Example #1 form empty:
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/b913be02-8352-4c2e-9c9b-626485856a75)

Example #2 form with invalid inputs:
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/94eeabc4-9f7e-483e-9c2e-c8ed8523df09)

Example #3 form with validinputs:
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/cf1c9c3b-f2aa-4bea-8226-04e248fe550c)

**Comment by PriBaez** [comment]
@DLeonProyects @DanielDD-UNPHU I don't think what you call invalid characters should be. I understand that it is a username and there are people who use those characters to give a touch of personalization to their name in the app.

**Comment by lopezbec** [comment]
This is a non-critical issue since at first the app/Prototype will be used in very controlled environments.   So don't work on this until other issues are completed

**Comment by Elmerluis0129** [comment]
Issue fixed!
