### ISSUE TITLE
Improve Closing Management in Quiz: or add 'I Prefer Not Answer' Button

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#54]
We have identified inconsistent behavior in the application related to Quiz closing. Currently, if a user closes the Quiz, the application allows them to continue and access the Dashboard without problems. However, this flow may not be best suited to ensure that users complete the Quiz or make a conscious decision about participating in it.

2. Automatic Closing of the Program: Implement a functionality where, if the user closes the Quiz, the application closes automatically. This would ensure that the user can only access the Dashboard after completing the Quiz.

Error page:
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/1f626645-51e6-48af-92b9-418ef85deac9)

**Comment by lopezbec** [comment]
The users would initially use this app in a controlled environment, so this is not as critical.

Nevertheless, the user needs to complete the survey to move forward. Hence, make sure that If the user does not complete the survey, it cannot play the application

**Comment by Elmerluis0129** [comment]
Already Fixed. User cannot access to the questions without completing the quiz (Being new user) or introducing their name already registered.
