### ISSUE TITLE
Implementation of Control Points to Avoid Infinite Accumulation in Slides Backwards

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#56]
A critical flaw has been identified in our application's scoring system related to navigation between question slides. Currently, when a user completes a question correctly and advances to the next slide, they get points for that answer. However, if the user decides to use the back button to return to the previous question, the application allows them to answer again and accumulate more points. This lack of control allows users to earn points infinitely by repeating the same process, which compromises the integrity of the scoring system.

To address this issue, we propose to implement logic that controls and limits point accumulation in the following ways:

1. Repeated Scoring Restriction: Once a user has answered a question correctly and earned points, that action should not award more points if the user returns to the same question.

2. Answer Record: Implement a system that records which questions have been answered correctly to avoid awarding additional points for repeated answers.

Capture #1 with 11 XP:
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/e8f0690d-3c16-4e57-90ba-5ae1cbb0ff99)

Capture #2 If you look at this screenshot I got 21 points simply by going back and completing the quiz again:
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/0463accc-f75f-42bc-99f1-9ab59926ee8d)

**Comment by Elmerluis0129** [comment]
Fixed, I just need to integrate it and upload it to the repo. I will close this issue once that done, meanwhile it'll keep open, so I don't forget.

**Comment by Elmerluis0129** [comment]
Fixed!
