### ISSUE TITLE
Reset Drag and Drop State When Using Back Button

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#57]
We have identified an issue in the Drag and Drop functionality of our app. Currently, if a user drags a response to its corresponding location and then decides to use the back button to return to a previous page or section, the selected response remains "pasted" or registered in the console. This persistence of the response is undesirable as it does not reflect the current state of the user interface after rolling back.

To solve this problem, we suggest implementing logic that resets the state of the Drag and Drop activity every time the user presses the back button. This would imply:

1. Clean up any responses that have been dragged and dropped into the console.

2. Restore the initial state of the Drag and Drop activity, as if the user had never interacted with it.

Capture #1:

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/c4fd822e-fca7-4e88-a9fc-99d344472fb0)

Capture #2 After pressing Back button
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/29cbd341-0937-4dd3-a6b8-7d8eef880ed4)

**Comment by PriBaez** [comment]
@DanielDD-UNPHU @DLeonProyects @lopezbec This issue only applies to Drag and Drop or should it be applied to another type of content/page like multiple choice or complete blank space?

**Comment by DLeonProyects** [comment]
> @DanielDD-UNPHU @DLeonProyects @lopezbec This issue only applies to Drag and Drop or should it be applied to another type of content/page like multiple choice or complete blank space?

Hello Priz, I only reported it to Drag and Drop, but I should wait for @lopezbec  response

**Comment by PriBaez** [comment]
If it is only for Drag and Drop type, I already have a solution that I am trying. If there must be more than Drag and drop type then I must make some adjustments

**Comment by lopezbec** [comment]
@DLeonProyects , not need to wait for me to get this question/issue addressed.

Anyone can easily check (by testing the app) if the questions get resisted when we click te back button or not

**Comment by PriBaez** [comment]
@lopezbec Ok. In the scenario that the user goes back more than one page, should all the previous ones be reset or only the last one reached?

**Comment by lopezbec** [comment]
Any question that has been "sent" (the user clicked "enviar") should not be reset. Only the questions in which the user has selected an answers but has not submitted, it should not be reset. Hence, it should only be one page
