### ISSUE TITLE
Missing lessons in Module 3

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#6]
The last two lessons in module 3 are missing. 

- While loops.

- Break and continue.

![ju](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/eedc47c8-25d7-4c32-b0dd-b17d67d8d969)

**Comment by DLeonProyects** [comment]
Solved.

**Comment by DanielDD-UNPHU** [comment]
Solved.
