### ISSUE TITLE
Add a feature to automatically/easly enable and disable game features

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#60]
The app needs to have a feature that gives a txt file, in which you could have a list of our game features as a boolean, the app would enable or disable some of our game features.  For example, given:

1) 
Leaderboard=false, 
points=false, 
progress=false

It should look like:
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/245394fd-6852-4a2a-af10-7deea90d013d)

2) 
Leaderboard=false, 
points=false, 
progress=true,

It should look like:

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/f50e109d-40b0-4d94-9055-5f229ae36412)

3) 
Leaderboard=false, 
points=true, 
progress=false,

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/072a4a0e-b1e4-44ad-8792-9ee1d9b59d1a)

4) 
Leaderboard=true, 
points=false, 
progress=false,

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/7a7f80b7-73b8-44ca-9777-bafe8b72d582)

5) 
Leaderboard=true, 
points=true, 
progress=false,

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/176cb794-8e01-44b4-bad0-b720f7f0ffa6)

AND SO ON

It should look like:

**Comment by PriBaez** [comment]
@lopezbec  I imagine that the generation of the file is linked to the part of marchine learning that evaluates the type of player. For now, do I just create a dummy file that does this same thing?

I guess you have to link it in some way to its respective user, right?

**Comment by lopezbec** [comment]
Hi  @PriBaez  you are correct, there would be a different script that will be used as input the response from the users of the survey (the ones in "/Usuarios_respuestas_entrevistas"), and as output will generate this file. Hence, for now, use a "dummy" file. I will use that as a reference for the format of the other script.

**Comment by PriBaez** [comment]
@lopezbec It would not be better to use a Json file since its key-value structure is more convenient for the tools intended for reading and writing it, which are an internal dependency of python.

**Comment by lopezbec** [comment]
I dont care which file format it uses, as long as it is a standard format. Whatever is easier. For this file, it can be as simple as a ".txt" file with 3 lines
