### ISSUE TITLE
Code playground consistency

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#63]
It looks like there are two ways to open/access the "code playground" : the one in Lesson 1 page 5 (which does not work)  and the ones in the other lessons (like 2 nd 3). Ensure there is consistency

Moreover, for the one in Lesson 3, a bit more instructions is needed since it is not clear whether the user needs to click "continual" to actually be allowed to open the code playground (lesson 2 does says something but not clear that it will be for the code playground).  

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/64444406-3e4f-4ddd-8824-1bc0507bd3f1)

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/25b7c2dd-0cd7-4a5e-a9cc-0a409b6ee752)

**Comment by Elmerluis0129** [comment]
Fixed!
