### ISSUE TITLE
Integrate Code playground into app

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#67]
Integrate the code plyground into the app (that is not as a separate window). That way users don’t need to close it after done, but it will happen automatically once they go to the next page (hence, a next page button also needs to be added here).

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/98b0d5db-0018-45dc-8aa4-9076b1bdf7dc)

**Comment by Elmerluis0129** [comment]
Fixed
