### ISSUE TITLE
Modules drop bigger in main menu

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#68]
In the “menu” page make the “modulos” drop down part bigger and in the middle. (we might even think of adding some type of progress bar for the modules or test other ways to clearly show the module progress of users

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/9cf83289-06fe-43c7-a4be-6b54cbe4c357)

**Comment by DLeonProyects** [comment]
Done!
