### ISSUE TITLE
Repeated content in module 2

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#7]
The content is repeated in the page module 2, lesson 2, page 10. It's the same for page 8 and 10.

- _Page 8_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/e93821eb-8e19-41b1-b2d9-597f2bdee557)

- _Page 10 (duplicate)_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/63482d07-077e-4dfd-b7fc-b0f5eacc115f)

**Comment by Elmerluis0129** [comment]
Esto es Daniel que tiene que arreglarlo, ya que él es el que se encarga de crear esos json.

**Comment by PriBaez** [comment]
Este issue no es tuyo @Elmerluis0129, no tenias que trabajarlos todos (por ejemplo, los de Tag JSON)

**Comment by josealfredomatias493** [comment]
Issue completed.
