### ISSUE TITLE
Adding  badget  system (     Sistema de Insignias)  as a new game element

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#79]
We need to think and work on adding a  Badge System into the game.

Pls work on a unique branch and DO NOT merge with the main until approved.

This badge system needs to be implemented as modular as possible to minimize the impact/disruption in other parts of the system.

The idea is after meeting some "achivements/milestones" the user will collect some badges. When a badge is achieved a new window should open for a few sec showing the image of the badge, its name, and a short description of the achievement. This system needs to access/tap/look at the user in-game data to check when a given achievement was met.

Example of achievements (pls generate more):

1) "first correct response"
2) First code playground interaction (try to find better names too)
3) 5 correct responses in a row, etc
(we need to have at least 10-15 achievements).

We need to think about how we would allow users to access/see all their budgets, it can be next to the leaderboard, in the main menu page but it needs to be independent from any other game element since we will enable and disable other elements depending on the user.

**Comment by lopezbec** [comment]
@PriBaez  could you confirm if you were thinking/already working with something like this a long time ago?

**Comment by PriBaez** [comment]
@lopezbec yes, its already developed, however I need to check what I did that time with the feature.

**Comment by PriBaez** [comment]
@lopezbec I gonna took this issue.
