### ISSUE TITLE
Code playground do not allows users input via "input()"

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#82]
The code for the code playground is running whatever is typed into the console as a subprocess. That is, it saves everything typed as a script and then is run and it output shown later (see lines 73-77 here: https://github.com/lopezbec/AI_Gamification_Python/blob/main/command_line_UI.py)

One potential solution is to use 'subprocess.Popen". Based on ChatGPT here is a potential solution that would need to be modified to fit out needs:

'The subprocess.run() function executes the specified command in a subprocess. If you want to simulate user input using input() within the subprocess, you can't directly achieve it with subprocess.run().

subprocess.run() doesn't interact with the standard input/output streams of the subprocess once it's launched. Instead, you might consider using subprocess.Popen() which allows you to communicate with the subprocess's standard streams.

Here's an example of how you might achieve this:'

`import subprocess

#Launch the subprocess
proc = subprocess.Popen([sys.executable, script_filename],
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT)

#Send input to the subprocess
user_input = b"your_input_here\n"  # Add '\n' to simulate hitting Enter after input
proc.stdin.write(user_input)
proc.stdin.flush()  # Ensure input is sent

#Read output from the subprocess
output = proc.stdout.read()

#Wait for the subprocess to finish
proc.wait()

#Close the subprocess's stdin to signal that no more input will be sent
proc.stdin.close()

#Decode the output from bytes to string
output_str = output.decode('utf-8')

print(output_str)
`
This script will launch the subprocess, send input to it, read its output, and then wait for it to finish. You can adjust this to fit your specific use case. Remember to handle errors and exceptions appropriately.

**Comment by lopezbec** [comment]
Did you test everything after integration?  if so let me know where it was push to to check (pls send me an email)

**Comment by josealfredomatias493** [comment]
Good night,

I have not pushed it to main yet. If I can do so, i will proceed and test.

Best regards,
JM

**Comment by lopezbec** [comment]
pls do it in a brach 1st and once you have tested everything (that is your implementation work and the other existing features still work in every page/module/lession) you can merge

**Comment by josealfredomatias493** [comment]
Got it. I should be merging tomorrow. I am looking the logics for the quizz
too.

Best regards,
JM

**Comment by lopezbec** [comment]
@josealfredomatias493 

the solution implemented is fine. However, to avoid confusion, only implement this solution in the instances in which a "input" is expected. You can manually identity all this, or create a scrip that read the JSON files of the question and is the keyword "input" is identify implement your solution, otherwise implement the old solution

**Comment by josealfredomatias493** [comment]
Good morning,

Perfect. I will do so.

Best regards,
JM
