### ISSUE TITLE
the XP score is not reflected correctly.

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#9]
The score is sometimes marked when the correct answer is selected, then returns to 0.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/c7542e57-51bd-46ca-9dd6-72b48101ff9d)

**Comment by Elmerluis0129** [comment]
I've been working in this one as well, and it turned to be harder than I expected. But I will continue working on it to see if I can fix it.

**Comment by Elmerluis0129** [comment]
Fixed. Im closing it!
