### ISSUE TITLE
Integrate Points System with quizzes

### ISSUE THREAD

**Issue by Elmerluis0129** [lopezbec/AI_Gamification_Python#94]
Connect quizzes with the points system to award points based on performance. Is almost the same methodology you guys i think @PriBaez used. Don't remember but anyone that did it should work on this. @lopezbec @josealfredomatias493 @alfredxp It doesn´t matter if you prefer to make a new system point for these quizzes or to integrate the old one. 

Update the user's total points after completing a quiz.
Display the points earned for each quiz attempt.

Please do not forget to text it before marking it as completed. Tag me once you got it updated so i can check it out. Might work a video from your POV so i now what you did.

**Comment by Elmerluis0129** [comment]
Here we can try making a new point system to see if it works ! @lopezbec

**Comment by lopezbec** [comment]
It should be linked to the same point system as the overall app (NOT a new separate one) 

We can add new code logic, separate from the original point system logic, that after completing a quiz it updates the "points"/score variable.

**Comment by PriBaez** [comment]
@Elmerluis0129  @lopezbec Is this issue already in progress?  If not, I will assign it to myself.

**Comment by PriBaez** [comment]
@lopezbec is this what we are trying to achieve with this issue?
![image](https://github.com/user-attachments/assets/432fbe85-c5a9-4060-ac23-a2d5fa1b5520)
