### ISSUE TITLE
 Add Additional Game Elements to the quizzes (Leaderboard)

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#96]
I am dividing issues #95  into multiple issues , one per game feature: This is for Leaderboard

Ensure all other game elements (such as progress bar) are functional with the quizzes.
Test each game element for consistency and expected behavior during quiz interactions.

Please do not forget to text it before marking it as completed. Tag me once you got it updated so i can check it out. Might work a video from your POV so i now what you did.

**Comment by Elmerluis0129** [comment]
Issue Completed. 

Here's my POV:

https://github.com/user-attachments/assets/cb595365-78e6-4acf-ac76-f6978f330cc7

**Comment by Elmerluis0129** [comment]
@lopezbec

**Comment by lopezbec** [comment]
Make sure to test all modules sequence work correctly with a new and repeated user (that is try it with a unique name, like testelmerdostree, go over multiple modules, close the app and try the same user again)

With a new user, I cannot open the Module 1 lesson4

**Comment by Elmerluis0129** [comment]
Issue Fixed. Try again. You can now open all lessons. @lopezbec
